### ISSUE TITLE
Serpentine Helm issue

### ISSUE THREAD

**Issue by Jos-Dalhuisen** [geheur/weapon-charges#31]
When you have the Serpentine helm in your bank or inventory, all the other charges from gear/weapons in the same area (banktab or inventory) are not showing anymore. When putting it back into the bank the inventory is working fine again. The Serpentine is never showing any charges.

Maybe already known, but thought I'd share.

**Comment by geheur** [comment]
can you send me your client.log?

To find the logs, you can do one of the following:
- Open the screenshot directory by right-clicking 📷 Camera button, navigate 1 directory up, then open logs folder.
- Navigate to %userprofile%\.runelite\logs on Windows or $HOME/.runelite/logs on Linux and macOS.

Upload the log files named client.log or client (no date), or send it to me on discord (geheur#4578)

**Comment by sillabick** [comment]
Same issue here with the Serp helm. Other items actually do sometimes display, but it depends on the location of the Serp helm in your inventory. If the items are next to it or after it in inventory order, then the charges don't display. Serp helm charges just straight up don't display. This is my first time using the plugin.

**Comment by geheur** [comment]
if you can send me your logs like I described in my other comment in this issue I can look into this.

**Comment by mheine** [comment]
Not sure if this is related; but would guess as such: a NullPointerException is thrown if you run RuneLite (and this plugin) via  console, and it seems to also concern the Serp Helm.

Log snippet:
```
java.lang.NullPointerException: Name is null
	at java.base/java.lang.Enum.valueOf(Enum.java:271)
	at com.weaponcharges.WeaponChargesConfig$SerpModes.valueOf(WeaponChargesConfig.java:160)
	at com.weaponcharges.WeaponChargesPlugin.getSerpHelmDisplayStyle(WeaponChargesPlugin.java:1067)
	at com.weaponcharges.WeaponChargesItemOverlay.renderItemOverlay(WeaponChargesItemOverlay.java:88)
	at net.runelite.client.ui.overlay.WidgetItemOverlay.render(WidgetItemOverlay.java:112)
	at net.runelite.client.ui.overlay.OverlayRenderer.safeRender(OverlayRenderer.java:735)
	at net.runelite.client.ui.overlay.OverlayRenderer.renderOverlays(OverlayRenderer.java:328)
	at net.runelite.client.ui.overlay.OverlayRenderer.renderAfterLayer(OverlayRenderer.java:250)
	at net.runelite.client.callback.Hooks.drawLayer(Hooks.java:567)
	at client.hy(client.java:47164)
...
	at client.im(client.java:4317)
	at client.bt(client.java:1204)
	at bm.by(bm.java:379)
	at bm.run(bm.java:333)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by mheine** [comment]
At a glance this seems like it could be because there seems to be no way to set the "Display Style" for the Serp Helm, and the default value causes an error

**Comment by geheur** [comment]
thanks mheine, that makes it easy to fix https://github.com/runelite/plugin-hub/pull/4317
